import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'tang' at '11/28/15 4:20 PM' with Gradle 2.6
 *
 * @author tang, @date 11/28/15 4:20 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    }
}
